### Get all
GET http://213.230.99.253:8080/admin/profile/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHcmVlZCIsInJvbGUiOiJST0xFX0FETUlOIiwiaWQiOiJkYjdhNjU3OS1jZDJjLTRkNGQtOTY4NS1jYTJmNWM1MTcyMDYiLCJpYXQiOjE3NTcxNjc4MTcsImV4cCI6MTc1NzI1NDIxN30.t_6a-kqGGfmGNoPKVSTsQ9D04TTYls2ieoC3iH60fLo41vFnV8_cI9uCWj2eaPZpHzNSryS-gaZW-nFpGUZT8w

### Get all
GET http://localhost:8080/admin/profile/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHcmVlZCIsInJvbGUiOiJST0xFX0FETUlOIiwiaWQiOiJiYzc1ODUwNi05NjAxLTQ1MmUtOTM0Ny1mNGNiNjY4YjU0M2YiLCJpYXQiOjE3NTcxNjgyOTMsImV4cCI6MTc1NzI1NDY5M30.XsOe9gQgHVlcUPHKKSUureYmj9aEJH6GYcVQm9SQ_B4rxfo8HFEyp52rvxad8P4MEagzz2EUrhiS4k6FqC1LPg


